name: CI Pipeline

on:
  push: [main]

jobs:
  build:
    runs-on: ubuntu latest

    step:
      - name: checkout code
        uses: action/checkout@v5

      - name: Set up Node.js
        uses: action/setup-node@v5
        with:
          node0version: 18
      - name: Install Dependency
        uses: npm Install

      - name: Run Test
        uses: npm test
